name: Testing

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action
        uses: ./
        with:
          pipeline_name: rest_api_pokemon
          destination: duckdb
          dataset_name: rest_api_data
          endpoint_url: https://pokeapi.co/api/v2/
          resources: pokemon berry location

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "data updated"
